[package]
name = "swf-monitor"
version = "0.1.0"
authors = ["Adrien Le Guillou <git@aleguillou.org>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.23.0" }
